# This workflow will pass tests of module passed by input
name: oorq
on:
  workflow_dispatch:
  pull_request: # PR
jobs:
  erp-tests-module:
    uses: Som-Energia/openerp_som_addons/.github/workflows/reusable_workflow.yml@main
    with:
      module: oorq
      pyversion: '["2.7", "3.10"]'
    secrets:
      ACCESS_TOKEN_GA: ${{ secrets.ACCESS_TOKEN_GA }}
      ESIOS_TOKEN: ${{ secrets.ESIOS_TOKEN }}
      SRID: ${{ secrets.SRID }}
